# Generated by Django 3.0.4 on 2020-04-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='datetime',
            field=models.DateField(null=True),
        ),
    ]
